### ISSUE TITLE
Fatal error on start

### ISSUE THREAD

**Issue by Jomosoto** [MOROway/moroway-app-oc#1]
Android 6, BlackBerry Dtek 50

When I launch the app, I see the icon, but after that "fatal error" appears on the screen.
![Screenshot_20210301-183711](https://user-images.githubusercontent.com/40580158/109536187-b9d3b880-7abd-11eb-8ba7-26a85fa8ab44.png)

**Comment by jonathanherrmannengel** [comment]
Thanks! Should be fixed with v7.1.1. Will take a few days to get to F-Droid…

**Comment by jonathanherrmannengel** [comment]
@Jomosoto v7.1.1 is live. Does it work now?

**Comment by Jomosoto** [comment]
No. I have the same error in the new version

**Comment by Jomosoto** [comment]
I solved it by resetting the app

**Comment by m65v19** [comment]
Not solved for me. I resetted and reinstalled the app, but Fatal Error still at launch
![Screenshot_2021-04-05-16-00-44](https://user-images.githubusercontent.com/15930110/113567471-1e87b300-9628-11eb-936e-2ea8254d6888.png)

**Comment by jonathanherrmannengel** [comment]
@m65v19 ok, thanks. could you tell me what Android version you use?

**Comment by m65v19** [comment]
Android 5.1.1 
Device is Sony SGP612

**Comment by jonathanherrmannengel** [comment]
Should be fixed with v7.1.2. Will take a few days to get to F-Droid… Can you confirm then?

**Comment by m65v19** [comment]
Yes, of course. I will waiting.

**Comment by jonathanherrmannengel** [comment]
@m65v19 v7.1.2 is live. Does it work now?

**Comment by m65v19** [comment]
@jonathanherrmannengel 
Hello. I installed 7.1.2 and it is works. Thanks you very much.

**Comment by jonathanherrmannengel** [comment]
great news
